//
//  Constants.swift
//  On The Map
//
//  Created by Bryan's Air on 7/9/18.
//  Copyright © 2018 Bryborg Inc. All rights reserved.
//

// MARK: Constants
struct Constants {
    
    // MARK: API Key
    static let ApiKey = "QuWThTdiRmTux3YaDseUSEpUKo7aBYM737yKd4gY"
    static let ParseApplicationID = "QrX47CA9cyuGewLdsL7o5Eb8iug6Em8ye0dnAbIr"
    
    static let ObjectId = ""
    //Description: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    //Parse Type: String
    //Example Value: 8ZExGR5uX8
    
    static let UniqueKey = "NUMBER"
    //Description: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
    //Parse Type: String
    //Example Value: 1234
    
    static let FirstName = ""
    //Description: the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in your app (see above)
    //Parse Type: String
    //Example Value: John
    
    static let LastName = ""
    //Description: the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in your app (see above)
    //Parse Type: String
    //Example Value: Doe
    
    static let MapString = ""
    //Description: the location string used for geocoding the student location
    //Parse Type: String
    //Example Value: Mountain View, CA
    
    static let MediaURL = ""
    //Description: the URL provided by the student
    //Parse Type: String
    //Example Value: https://udacity.com
    
    static let Latitude = ""
    //Description: the latitude of the student location (ranges from -90 to 90)
    //Parse Type: Number
    //Example Value: 37.386052
    
    static let Longitude = ""
    //Description: the longitude of the student location (ranges from -180 to 180)
    //Parse Type: Number
    //Example Value: -122.083851
    
    static let CreatedAt = "DATE"
    // Description: the date when the student location was created
    //Parse Type: Date
    //Example Value: Feb 25, 2015, 01:10
    
    static let UpdatedAt = "DATE"
    //Description: the date when the student location was last updated
    //Parse Type: Date
    //Example Value: Mar 09, 2015, 23:34
    
    static let ACL = "ARRAY?"
    //Description: the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry
    //Parse Type: ACL
    //Example Value: Public Read and Write

    

}
